### ISSUE TITLE
Revisar cuando ya active la cuenta despues de la prueba gratuita

### ISSUE THREAD

**Issue by ArnoldHueteG** [bigdataanalytics-fundaciontelefonica/bigdata_analytics_ft_2022_g7#7]
En la clase encontramos que el proyecto no tiene cuenta de facturacion asociada.

**Comment by Johao23** [comment]
primer comentario

**Comment by LizbethGiraldo** [comment]
segundo comentario

**Comment by AlexanderHOB** [comment]
Tercer comentario

**Comment by jaimesolisg** [comment]
ultimo comentario!

**Comment by Deygerson-Mndz** [comment]
Nuevo comentario, que facil esto de los ISHUS :)

**Comment by AndresSotoA** [comment]
interesante.

**Comment by ncarrascoca** [comment]
Comentario para que no se olvide ✌️

**Comment by AlexMezaDB** [comment]
Mismo problema

**Comment by boniescarletpg** [comment]
Ya activé la cuenta sin inconveniente

**Comment by luisfernandosolis** [comment]
mismo problema

**Comment by Johao23** [comment]
mismo problema
